server.port=${PORT:8080}

spring.application.name=amazon-ec

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/amazon_ec}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

dell.base-url=${DELL_BASE_URL:http://localhost:8081}
smbc.base-url=${SMBC_BASE_URL:http://localhost:8082}

products.sync.api-key=${SYNC_API_KEY}